# -*- coding: utf-8 -*-
"""deploying.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eUZ-qpcQScTCIPeXkhHvsEeqyF7is0C4
"""

import pickle
with open('/content/drive/MyDrive/Programming for AI/tokenizer.pickle', 'rb') as handle:
    sentence_tokenizer = pickle.load(handle)

import tensorflow as tf

max_length=50
sentences_shuffled="አስቀድሜ ጥያቄዬ በጨዋነት በውስጥ መስመር እንዲደርስዎ አድርጌ ፍትህን ለማገዝ ብሞክር  እርስዎ የመፅሀፍ ቅዱሱ የዳዊት  ኦሮዮንን መንገድ በመምረጥዎ በይፋ ለመፃፍ ተገድጃለሁ  አሁንም መረጃው እንዴት እሱ ጋር ደረሰ የሚለውን ውትወታ ትተው በማንኛውም መንገድ ቀጥተኛ ምላሽ ይስጡኝ   ከመስከረም   ወዲያ አሁን ያለሁ መንግስት ህጋዊ የስራ ዘመኑ ስለሚያበቃ የባለአደራ መንግስት እንዲቋቋም ሆኖም አሁን ያለው የአብይ መንግስት አስፈፃሚ አካል የመንግስትን የእለ ተእለት ተግባራትን እየከወነ ምርጫ እስኪደረግ ለ አመት እ".split()

sequences=sentence_tokenizer.texts_to_sequences(sentences_shuffled)
padded_sequence=tf.keras.preprocessing.sequence.pad_sequences(sequences,maxlen=max_length,padding="pre",truncating="pre")

padded_sequence

importedModel = importedModel=tf.keras.models.load_model(
    "/content/drive/MyDrive/Programming for AI/model_6.h5", custom_objects=None, compile=True, options=None)
prediction=importedModel.predict(padded_sequence)

prediction

from google.colab import drive
drive.mount('/content/drive')