# Generated by Django 4.1.7 on 2023-02-15 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_created_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 15, 9, 50, 19, 132360)),
        ),
    ]
