# Generated by Django 4.1.7 on 2024-05-24 16:34

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_alter_comment_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="post",
            name="audio",
            field=models.FileField(
                blank=True, null=True, upload_to=post.models.upload_to
            ),
        ),
    ]
